# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - NFS kernel server
LUCI_DEPENDS:=+luci-base +nfs-kernel-server

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Gemini CLI

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
